development: &common
  # The Redis pub/sub channel that Pibi and PibiRealtime communicate over.
  #
  # This *must* match with the config of Pibi.
  channel: 'pibi_realtime'

  # PibiRealtime uses Redis for two purposes: accepting commands from Pibi,
  # and storing Faye state.
  #
  # The following is shared for both purposes:
  redis:
    id: 'pibi_realtime'
    host: 'localhost'
    port: 6379
    password:
    # This must match the Redis database Pibi uses.
    db: 0
    # Redis will automatically re-connect and re-publish pending commands if
    # the connection times out within the specified amount of seconds:
    timeout: 5.0
    tcp_keepalive: 0
  faye:
    # WebSocket/Long-Polling timeout:
    timeout: 25
    redis:
      # Faye state should optimally be stored in a different database than the
      # one Pibi uses:
      database: 1

production:
  <<: *common

test:
  <<: *common